add information about membership levels and evaluation
b4ck5p4c3/0x08.in pull request #155
Opened 2020-01-28 20:01 UTC by kaero

2020-01-29 09:56 UTC, aanper commented on _pages/evaluation.md
> +- участник представит вас остальным в течение 1 недели остальным участникам
Здесь неоднозначное чтение.
Это означает, что участником можно стать спустя неделю после начала процесса?

2020-01-29 09:56 UTC, aanper commented on _pages/evaluation.md
> +Чтобы стать участником 20 уровня, нужно чтобы другие участники 20 уровня приняли кандидатуру из числа участников 10 уровня. Кандидатуру нового участника 20 уровня может представить любой существующий
вот примерно здесь я стал охреневать от терминологии и цифр 10 и 20.
Предлагаю
s/участники 20/доверенные участники
s/участники 10/участники

2020-01-29 09:56 UTC, aanper commented on _pages/evaluation.md
> +## Участник специального назначения
s/Участник специального назначения/Дежурный

2020-01-29 09:56 UTC, aanper commented on _pages/evaluation.md
> +Один из участников 20 уровня и выше. Человек ответственный за помещение хакспейса. Имеет право вето на любые действия участников, разрушительные для помещения.
Стоит отметить, что дежурный — переходящая должность.

Стоит отметить, что если в хакспейсе есть несколько участников 20 уровня, то по взаимной договоренности должен быть определен дежурный, чтобы не было ситуации, когда _все в говно и никто не отвечает_

2020-01-29 09:57 UTC, aanper commented
/d

2020-01-29 13:59 UTC, kaero commented on _pages/evaluation.md
> +## Участник специального назначения
Нет, это арендатор помещения, не дежурный.

2020-01-29 13:59 UTC, kaero commented on _pages/evaluation.md
> +Один из участников 20 уровня и выше. Человек ответственный за помещение хакспейса. Имеет право вето на любые действия участников, разрушительные для помещения.
Это не дежурный. Дежурный этой документацией не определен.

2020-01-29 14:29 UTC, aanper commented on _pages/evaluation.md
> +## Участник специального назначения
А, понял

2020-01-29 14:50 UTC, kaero commented on _pages/evaluation.md
> +- участник представит вас остальным в течение 1 недели остальным участникам
допишу: "..., и по результатам обсуждения сообщит вам приняты вы или нет"

2020-01-29 15:45 UTC, kaero commented on _pages/evaluation.md
> +- участник представит вас остальным в течение 1 недели остальным участникам
нет, не напишу, там же следующий пункт про результат

2020-01-29 16:29 UTC, heeeyflo requested changes

2020-01-29 16:29 UTC, heeeyflo commented on _pages/evaluation.md
> +Имеют все те же права, что и участники 20 уровня, а также:
Мне кажется что это не очень правильная идея. 
Получается что у нас есть кулдаун (L31) для участников Л10 перед апгрейдом до Л20, но для резидентов такого кулдауна нет? Несколько опасная схема, потому что описанная логика подразумевает необходимость в мгновенном принятии решения об (условно) человеке с улицы, с которым участники Л20 могут быть даже не знакомы и видеть вообще впервые.

2020-01-29 16:29 UTC, heeeyflo commented on _pages/evaluation.md
> +Имеют все те же права, что и участники 20 уровня, а также:
Опасения связаны, в основном, с так называемым «правом голоса» и вообще статусом участника Л20, который подразумевает что персона с таким статусом достаточно активно принимает участие в жизни спейса.

2020-01-29 18:41 UTC, kaero commented on _pages/evaluation.md
> +Имеют все те же права, что и участники 20 уровня, а также:
> подразумевает необходимость в мгновенном принятии решения об (условно) человеке с улицы, с которым участники Л20 могут быть даже не знакомы и видеть вообще впервые.

Так участники откажут ему в таком случае. К тому же количество резидентских мест заведомо органичено. 

Предложите, плз, какой-то другой процесс как реализовать резидентские места. Как мне кажется, за месяц человек, которому нужно рабочее место просто снимет себе что-то другое, нежели будет ждать, без гарантированного результата к тому же. Подход "вот ваш стол за 10к, но прав у вас нет и ключей тоже" мне тоже не видится реализуемым. Ничего более лучшего в голову не приходит.

2020-01-29 18:44 UTC, kaero commented on _pages/evaluation.md
> +Имеют все те же права, что и участники 20 уровня, а также:
Можно еще выпилить резидентов из первой редакции или по крайней мере процесс их выбора, если это спорный момент.

Еще можно вообще избавиться от сущности резидентов, и оставить только два уровня частников, и ввести отдельно оплату личных рабочих столов и места для хранения для участников любого уровня.

2020-01-30 09:51 UTC, imcatwhocode commented on _pages/evaluation.md
> +Имеют все те же права, что и участники 20 уровня, а также:
> Подход "вот ваш стол за 10к, но прав у вас нет и ключей тоже" 
Не вижу проблем не эскалировать права до Л20, но выдать условные ключи. То есть, резиденты с улицы — это Л10 со столом и ключами, а чтобы получить преференции Л20 нужно проделать стандартный путь с голосованием и всем прочим по обычной схеме.

2020-01-30 11:11 UTC, kaero commented on _pages/evaluation.md
> +Имеют все те же права, что и участники 20 уровня, а также:
Кажется, что это предложение равно избавлению сущности резидента. Просто стол и место хранения не связано с уровнем участника. Получается, что "резидент с улицы" = Л10+стол+место, а "резидент из Л20"=Л20+стол+место.

2020-02-10 17:02 UTC, kaero commented
/a

2020-02-10 17:03 UTC, aanper commented
Давай обсудим еще раз на встрече звтра.
/d

2020-02-11 08:43 UTC, sntxerror commented on _pages/evaluation.md
> +- место для хранения своих проектов в бэкспейсе;
не место, возможность. кроме того если нужно хранение, то требуется приобрести контейнер нужного размере, тоже марки что в спэйсе за свой счет.

2020-02-11 08:43 UTC, sntxerror commented on _pages/evaluation.md
> +- возможность бронировать переговорку;
сейчас этот пункт лучше убрать,  так как доступ в переговорку вайолейтит изолированность резидентской зоны. когда будет доступная переговорка тогда добавим.

2020-02-11 08:43 UTC, sntxerror commented on _pages/evaluation.md
> +В бэкспейсе есть несколько видов участников.
Надо прямо тут перечислить какие, для чего это нужно. Ниже они раскрываюстя.

Например:

`У людей в бэкспейсе есть несколько ролей: гость, участник, суперучастник и резидент. У каждой роли свои возможости (например, права доступа), и обязанности (например ...).  `

2020-02-11 08:43 UTC, sntxerror commented on _pages/evaluation.md
> +*Резиденты* получают фиксированный стол и место для хранения в резидентской.
Стол они не получают) Они получают доступ к выделенному рабочему месту)

2020-02-11 08:43 UTC, sntxerror commented on _pages/evaluation.md
> +---
Нужно вернуть описание Гостя.

2020-02-11 08:43 UTC, sntxerror commented on _pages/evaluation.md
> +title: Как стать участником
Предлагаю другой заголовок  `Участие`

2020-02-11 08:43 UTC, sntxerror commented on _pages/evaluation.md
> +- возможность использовать ресурсы бэкспейса для своих проектов, в том числе расходные материалы;
Здесь нужно устаканить правило. 

Предлагаю обсудить правило в духе Рижского хакспейса: `Мелочь - беслптано, то что дороже X за штуку - можно забирать при условии что заказал в спэйс такое же`

2020-02-11 08:43 UTC, sntxerror commented on _pages/evaluation.md
> +- возможность стать *суперучастником*.
Так же они получают доступ в спэйс когда в нем есть суперучастник, или нет?

2020-02-11 08:46 UTC, aanper commented on _pages/evaluation.md
> +- возможность бронировать переговорку;
Вчера обсуждали этот момент, тоже думал об этом, но если участник в спейсе, то суперучастник тоже в спейсе и он может провести участника в переговорку и проследить, что он не трогает ничего в резидентской.
Если такой сценарий не устраивает, можем убрать.

2020-02-11 08:48 UTC, aanper commented on _pages/evaluation.md
> +- место для хранения своих проектов в бэкспейсе;
Согласен про возможность.

Про приобретение контейнера обсуждаемо.

2020-02-11 08:49 UTC, aanper commented on _pages/evaluation.md
> +В бэкспейсе есть несколько видов участников.
Да, согласен.

2020-02-11 08:49 UTC, aanper commented on _pages/evaluation.md
> +*Резиденты* получают фиксированный стол и место для хранения в резидентской.
+

2020-02-11 08:49 UTC, aanper commented on _pages/evaluation.md
> +---
`+`

2020-02-11 08:50 UTC, aanper commented on _pages/evaluation.md
> +title: Как стать участником
Может тогда «уровни участия» или около того.
Заголовок и правда не соответствует содержимому.

2020-02-11 08:53 UTC, aanper commented on _pages/evaluation.md
> +- возможность использовать ресурсы бэкспейса для своих проектов, в том числе расходные материалы;
Согласен, что стоит как-то зафиксировать, но к обсуждению.

В голову приходит пара примеров: 
* что если я взял какую-то старую плату, чтобы распаять на компоненты — стоимость не оценить, такую же не заказать, но вроде и не нужна никому.
* как оценить стоимость расходников?

2020-02-11 08:53 UTC, aanper commented on _pages/evaluation.md
> +- возможность стать *суперучастником*.
Да, наверное стоит написать это явно

2020-02-11 08:55 UTC, kaero commented on _pages/evaluation.md
> +- место для хранения своих проектов в бэкспейсе;
По моему это придирки к словам. Про контейнеры написано в хранении, можно поставить ссылку. Btw, это не соответствует не текущим записанным правилам про хранение, ни фактическому положению вещей: у правила не требуют, и у нас уже там широкое разнообразие различных контейнеров.

2020-02-11 08:58 UTC, kaero commented on _pages/evaluation.md
> +В бэкспейсе есть несколько видов участников.
> В бэкспейсе есть несколько видов участников, они перечислены ниже, также как их возможности, и то как ими стать.

2020-02-11 09:00 UTC, kaero commented on _pages/evaluation.md
> +---
Только что в нем написать? По моему *Гость* -- это любой, кто не попадает под другие определения.

2020-02-11 09:00 UTC, aanper commented on _pages/evaluation.md
> +- место для хранения своих проектов в бэкспейсе;
Обновил про хранение.
Предлагаю пока правило про контейнеры оставить за рамками, добавить позже.

2020-02-11 09:00 UTC, kaero commented on _pages/evaluation.md
> +- возможность использовать ресурсы бэкспейса для своих проектов, в том числе расходные материалы;
Как оценить стоимость вообще хоть чего-нибудь, что не новое?

2020-02-11 09:02 UTC, aanper commented on _pages/evaluation.md
> +В бэкспейсе есть несколько видов участников.
Обновил

2020-02-11 09:02 UTC, kaero commented on _pages/evaluation.md
> +- возможность стать *суперучастником*.
А у кого-то нет такого доступа? Мы же пускаем людей, когда у нас открыто. Участник от прохожего отличается только тем, что перечислено у него в этом списке. Про доступ мы обсуждали, что иначе получается, что единственное время, когда гости могут приходить -- это мероприятия и ДоД. Но это не соотвествует ни факту, ни желаемой норме (по крайней мере моей).

2020-02-11 09:03 UTC, NetBUG commented on _pages/evaluation.md
> +- возможность использовать ресурсы бэкспейса для своих проектов, в том числе расходные материалы;
У нас были две хорошие идеи.
1) «Давай больше, чем взял»
2) Список необходимого стаффа
=> логичнее всего на каждый взятый юнит просить принести что-то из этого списка, начиная от бумажных полотенец и заканчивая осциллографами на 10 Gs.
Хотя бы потому что если взяли одну из 15 RPi HW rev 1 model B, вряд ли спейсу нужно именно её компенсировать, гораздо полезнее на эти $25 притащить стоящего в списке актуального.

2020-02-11 09:03 UTC, aanper commented on _pages/evaluation.md
> +*Резиденты* получают фиксированный стол и место для хранения в резидентской.
Обновил

2020-02-11 09:05 UTC, NetBUG commented on _pages/evaluation.md
> +Имеют все те же права, что и участники 20 уровня, а также:
У нас же есть возможность принять Л20 голосованием. Совсем с улицы мы человека, наверное, не хотим, но если он был на паре мероприятий и внезапно захотел работать в спейсе — why not?

2020-02-11 09:06 UTC, kaero commented on _pages/evaluation.md
> +- возможность использовать ресурсы бэкспейса для своих проектов, в том числе расходные материалы;
Плюсую первую идею @NetBUG , вторая страдает той же проблемой оценки, на мой взгляд.

И у меня еще вопрос обязательности этой компенсации. Если она обязательная, то как вести учет потраченного и компенсированного?

2020-02-11 09:07 UTC, aanper commented on _pages/evaluation.md
> +---
Ну так и написать, у него тоже есть возможности и обязанности.

2020-02-11 09:07 UTC, aanper commented on _pages/evaluation.md
> +title: Как стать участником
М.б. `Роли`?

2020-02-11 09:10 UTC, aanper commented on _pages/evaluation.md
> +- возможность стать *суперучастником*.
Судя по вопросам в чате, люди как раз не понимают, что можно придти когда открыто, я думаю, явно написанное будет полезно.

2020-02-11 09:12 UTC, aanper commented on _pages/evaluation.md
> +- возможность использовать ресурсы бэкспейса для своих проектов, в том числе расходные материалы;
Может быть пока написать «возможность использовать ресурсы бэкспейса для своих проектов (при согласовании с суперучастником)» и оставить этот вопрос до прецедентного решения или дальнейших обсуждений

2020-02-11 09:46 UTC, imcatwhocode commented on _pages/evaluation.md
> +- возможность бронировать переговорку;
Я согласен с Лёней, имхо, лучше сейчас этот пункт убрать. Кроме проблем с проходом через резидентскую, встаёт ещё и задача «забронировать», а у нас для этого нет никакой инфраструктуры, равно как и самой переговорки в чистом виде — там тоже есть личные вещи, там часто лежит матрас и нет стола.

2020-02-11 09:49 UTC, aanper commented on _pages/evaluation.md
> +- возможность бронировать переговорку;
Ладно, давайте и правда пока идею с переговоркой уберем. Обновил

2020-02-11 13:19 UTC, kaero commented on _pages/evaluation.md
> +- возможность стать *суперучастником*.
Так не понимают этого не участники, кмк. Я по крайней мере не знаю ни одного участника, который этого не понимает, но моя выборка не равна полному списку участников без физического доступа

2020-02-11 13:20 UTC, kaero commented on _pages/evaluation.md
> +- возможность использовать ресурсы бэкспейса для своих проектов, в том числе расходные материалы;
> оставить этот вопрос до прецедентного решения

то есть до ближайшего чьего-то желания потратить резистор или кусок изоленты из коробки в общем пространстве?

2020-02-11 13:21 UTC, kaero commented on _pages/evaluation.md
> +- возможность бронировать переговорку;
> задача «забронировать», а у нас для этого нет никакой инфраструктуры

завести календарь, но пока мне не изветно ни одного конфликта доступа к переговорке

2020-02-11 13:49 UTC, aanper commented on _pages/evaluation.md
> +- возможность использовать ресурсы бэкспейса для своих проектов, в том числе расходные материалы;
До сих пор мы как-то существовали. Думаю, до ближайшего желания потратить что-то действительно ценное типа отладки или дорогой микросхемы.
Мб пока добавить правило «хочешь что-то использовать насовсем или деструктивно — спроси у суперучастника»

2020-02-11 13:50 UTC, aanper commented on _pages/evaluation.md
> +- возможность стать *суперучастником*.
У нас сейчас и участников не так много.
В любом случае: явное лучше неявного.

2020-02-11 18:31 UTC, merged