[wip] add publication rules
b4ck5p4c3/0x08.in pull request #28
Opened 2019-10-30 14:26 UTC by aanper

Предлагаю определить правила публикации, и, главное, репостов сообщений в информационные каналы (навеяно #15). Я не смог определиться с `<blacklist>`, прошу помочь.

2019-10-30 19:52 UTC, z4fd approved these changes

2019-10-30 20:18 UTC, z4fd requested changes
Ибо

2019-11-01 02:46 UTC, kaero commented
Кажется, что достаточно перенести твиттер в пункт 1 и во втором пукте слово "канал" заченить на "чат".

2019-11-01 08:08 UTC, aanper commented
Твиттер так устроен, что все ответы, например, тоже являются твитами в общей ленте. Поэтому создавать правило «писать только про место» нельзя.
Не вижу отличия политики твиттера от политики чата, даже несмотря на то, что контроль и правда осуществляется администраторами и мы пишем там от лица места.

2019-11-03 20:38 UTC, kaero commented
отклонено:
- консенсус между участниками дискуссии не достугнут
- прошло более 24 часов с момента последнего комментария с командой

2019-11-03 20:38 UTC, closed without merging