Добавляет на вики страницу о рабочих группах
b4ck5p4c3/0x08.in pull request #329
Opened 2020-12-01 23:06 UTC by sntxerror

2020-12-02 08:15 UTC, glitchcore commented on content/wiki/working-groups.md
> +Порой бывает не легко отличить требование от пожелания, но в общем случае можно разобраться задав собеседнику вопрос "почему". По ключевым фразам "я хочу" и "мне нравится" легко отделяются пожелания
добавить пробел после «предпочтения.»

2020-12-02 08:16 UTC, glitchcore approved these changes
ок, давайте попробуем

2020-12-02 08:25 UTC, sntxerror commented on content/wiki/working-groups.md
> +Порой бывает не легко отличить требование от пожелания, но в общем случае можно разобраться задав собеседнику вопрос "почему". По ключевым фразам "я хочу" и "мне нравится" легко отделяются пожелания
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 08:34 UTC, mike-lambert approved these changes

2020-12-02 10:20 UTC, glitchcore approved these changes

2020-12-02 10:56 UTC, adjofun commented on content/wiki/working-groups.md
> +*Под ответственностью мы понимаем, что участнику какой-либо группы предстоит, например, поддерживать сетевую инфраструктуру созданную группой, красить стену по итогу коллективного решения, чинить СКУ
Перечисление примеров не является гибким определением.
Предлагаю выкинуть понятие ответственности на мороз, и заменить его чем-то другим, имеющим больше смысла.

2020-12-02 10:56 UTC, adjofun commented on content/wiki/working-groups.md
> +Вступление в любую рабочую группу подразумевает что:
"подразумевает, что"

2020-12-02 10:57 UTC, adjofun commented on content/wiki/working-groups.md
> +- у вас есть опыт полезный для целей рабочей группы, либо вы желаете этот опыт приобрести
"опыт, полезный"

2020-12-02 10:57 UTC, adjofun commented on content/wiki/working-groups.md
> +В issue-анонсе, участники желающие присоединиться ко группе явно обозначают свое намерение в комментариях. Так же хорошим тоном будет описать, чем именно вы готовы помочь группе, для достижения её це
"участники, желающие присоединиться к группе, явно"

2020-12-02 10:58 UTC, adjofun commented on content/wiki/working-groups.md
> +Группа не нужна и перестает существовать если выполняется хотя бы одно из условий:
"существовать, если"

2020-12-02 11:00 UTC, adjofun commented on content/wiki/working-groups.md
> +- цель создания группы недостижима
По какому критерию цель рабочей группы начинает считаться недостижимой? И на каком этапе?

2020-12-02 11:00 UTC, adjofun commented on content/wiki/working-groups.md
> +Рабочие группы позволяют прозрачно делегировать решение вопросов в конкретной предметной области (например "интерьер") заинтересованным участникам и упростить коллективное принятие решений.
"(например, интерьер)"

2020-12-02 11:01 UTC, adjofun commented on content/wiki/working-groups.md
> +Чтобы выйти из рабочей группы нужно заранее предупредить участников группы о своем намерении её покинуть.
"группы, нужно"

2020-12-02 11:02 UTC, adjofun commented on content/wiki/working-groups.md
> +Рабочая группа не может существовать без цели, и важно её сформулировать. Эффективнее всего если цель достижима, её можно измерить, проверить и она ограничена во времени. (см [SMART](https://ru.wikip
"всего, если"
"проверить, и"

2020-12-02 11:03 UTC, adjofun commented on content/wiki/working-groups.md
> +Так же понадобятся ссылки на issues (задачи, проблемы, идеи) или на репозиторий в котором реализуется проект.
"репозиторий, в котором"

2020-12-02 11:03 UTC, adjofun commented on content/wiki/working-groups.md
> +Порой бывает не легко отличить требование от пожелания, но в общем случае можно разобраться задав собеседнику вопрос "почему". По ключевым фразам "я хочу" и "мне нравится" легко отделяются пожелания
"разобраться, задав"

2020-12-02 11:04 UTC, adjofun commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
"Решение, набравшее"

2020-12-02 11:06 UTC, adjofun commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
С чего бы вдруг участникам принимать решения за рабочую группу? Вроде бы вся ее польза в том, чтобы делегировать решения, малоинтересные большинству, туда.

2020-12-02 11:07 UTC, adjofun commented on content/wiki/working-groups.md
> +Будучи участником группы важно не только сохранять результат в рабочем состоянии, но и помогать участникам не входящим в рабочу группу в нем разбираться и пользоваться.
"группы, важно"
"участникам, не входящим в рабочую группу, в нем разбираться"

2020-12-02 11:08 UTC, adjofun commented on content/wiki/working-groups.md
> +Часто в спейсе возникают задачи требующие совместной работы, затрагивающие интересы участников и/или бэкспейса в целом. Раньше мы старались принимать решения по таким задачам консенсуально, но на пра
"задачи, требующие"

2020-12-02 11:36 UTC, sntxerror commented on content/wiki/working-groups.md
> +- цель создания группы недостижима
На любом этапе. Недостижимость цели это например наличие непреодолимых ограничений. Любое сочетание обстоятельств среды и действий людей, когда цель не может быть достигнута.

Пример:

Цель группы – проводить массовые оффлайновые события раз в месяц. Недостижима она потому что пандемия заставила нас ограничить оффлайновые мероприятия в бэкспейсе.

В такой ситуации нужно менять цель, либо закрывать группу.

2020-12-02 11:38 UTC, sntxerror commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
Различие мнений часто приводит к тому что без конфликта решение принять невозможно. Смысл в том, что такое различие мнений нужно разрешить третьей стороной. Третья сторона для участников группы это те, кого в группе нет.

2020-12-02 11:50 UTC, adjofun commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
Участники, заинтересованные в результатах от рабочей группы, и принимающие решения за нее, почему то будут находиться вне этой группы.
Фактически, подобная практика превратится в инструмент разрушения рабочих групп изза раздоров. Согласно такой логике, спейс давно закрывать пора.
Третья сторона, по идее, разрешает конфликт, а не внедряет свое решение за рабочую группу.

То есть, участвующие в группе делают это не ради своих целей добровольно, а ради того, чтобы остальные участники хотели работающий скуд, или там стены красивые, и ничего для этого не делали? А если красящие о цвете договориться не могут, то решение принимается за них, пускай красят как мы им сказали? Звучит как инверсия ответственности для меня.
Никто не захочет создавать никакие рабочие группы, если ими будут помыкать.

2020-12-02 11:57 UTC, sntxerror commented on content/wiki/working-groups.md
> +Часто в спейсе возникают задачи требующие совместной работы, затрагивающие интересы участников и/или бэкспейса в целом. Раньше мы старались принимать решения по таким задачам консенсуально, но на пра
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 11:57 UTC, sntxerror commented on content/wiki/working-groups.md
> +Будучи участником группы важно не только сохранять результат в рабочем состоянии, но и помогать участникам не входящим в рабочу группу в нем разбираться и пользоваться.
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 11:57 UTC, sntxerror commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 11:57 UTC, sntxerror commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 11:58 UTC, sntxerror commented on content/wiki/working-groups.md
> +Порой бывает не легко отличить требование от пожелания, но в общем случае можно разобраться задав собеседнику вопрос "почему". По ключевым фразам "я хочу" и "мне нравится" легко отделяются пожелания
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 11:58 UTC, sntxerror commented on content/wiki/working-groups.md
> +Так же понадобятся ссылки на issues (задачи, проблемы, идеи) или на репозиторий в котором реализуется проект.
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 11:58 UTC, sntxerror commented on content/wiki/working-groups.md
> +Рабочая группа не может существовать без цели, и важно её сформулировать. Эффективнее всего если цель достижима, её можно измерить, проверить и она ограничена во времени. (см [SMART](https://ru.wikip
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 11:58 UTC, sntxerror commented on content/wiki/working-groups.md
> +Чтобы выйти из рабочей группы нужно заранее предупредить участников группы о своем намерении её покинуть.
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 11:58 UTC, sntxerror commented on content/wiki/working-groups.md
> +Рабочие группы позволяют прозрачно делегировать решение вопросов в конкретной предметной области (например "интерьер") заинтересованным участникам и упростить коллективное принятие решений.
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 11:58 UTC, sntxerror commented on content/wiki/working-groups.md
> +- цель создания группы недостижима
Добавил подробностей 919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 11:58 UTC, sntxerror commented on content/wiki/working-groups.md
> +Группа не нужна и перестает существовать если выполняется хотя бы одно из условий:
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 11:59 UTC, sntxerror commented on content/wiki/working-groups.md
> +В issue-анонсе, участники желающие присоединиться ко группе явно обозначают свое намерение в комментариях. Так же хорошим тоном будет описать, чем именно вы готовы помочь группе, для достижения её це
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 11:59 UTC, sntxerror commented on content/wiki/working-groups.md
> +- у вас есть опыт полезный для целей рабочей группы, либо вы желаете этот опыт приобрести
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 11:59 UTC, sntxerror commented on content/wiki/working-groups.md
> +Вступление в любую рабочую группу подразумевает что:
919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 12:00 UTC, sntxerror commented on content/wiki/working-groups.md
> +*Под ответственностью мы понимаем, что участнику какой-либо группы предстоит, например, поддерживать сетевую инфраструктуру созданную группой, красить стену по итогу коллективного решения, чинить СКУ
Разделил 919abcf6a5e818603ba4b1ef46d5521dad5db5ab

2020-12-02 12:05 UTC, sntxerror commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
Ты почему то к этому относишься с позиции разрушения)

Есть задача покраски например стены, есть ответственная группа, в группе есть два разных решения, оба решения предоставляются на голосование, голосуют все.

Где здесь помыкание?

2020-12-02 12:08 UTC, sntxerror commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
> участвующие в группе делают это не ради своих целей добровольно, а ради того, чтобы остальные участники хотели работающий скуд, или там стены красивые, и ничего для этого не делали

почти что так, группа по определению создается чтобы заниматься задачами не в личных интересах, а в интересах других участников. 

Мы делаем СКУД не что бы он работал только с твоим пропуском. И более того какая то часть людей действительно для этого ничего не делает и не должна и это нормально.

2020-12-02 12:10 UTC, adjofun commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
А после этого голосования проигравший красит стену серебрянкой, потому что ему обидно :)
Раздор никуда не делся, решение саботировано, конфликт теперь находится за пределами рабочей группы. 
Если такое произойдет в нескольких группах сразу, подковерных битв хватит на три года вперед.

2020-12-02 12:11 UTC, sntxerror commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
Нет, предполагается, что вступая в группу человек соглашается с тем, что решения принимаются коллективно на общих условиях.

2020-12-02 12:13 UTC, sntxerror commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
"Подковерные" конфликты возможны и без рабочих групп и без бэкспейса.

В наших принципах подчеркивается, что предполагается стараться быть вежливыми друг другу. Вести "подковерные конфликты" исходя из наших принципов не вежливо.

Так же, не вежливо красить серебрянкой стену вопреки коллективному решению.

2020-12-02 12:17 UTC, sntxerror commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
Важно так же понимать, что мы никаких процессом и правилом не учтем все возможные сценарии.

Случай с конфликтом можно рассматривать более прецедентно.

2020-12-02 12:23 UTC, adjofun commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
И что делать участникам с этим "невежливо", когда стена покрашена уже?

Выражаясь аналогией, если вдруг за электрика начнет принимать решения о проводке жилец, то жилец имеет вероятность сгореть выше нормальной :) 

Говорить о конфликтах как о чем то "невежливом" неэффективно. Еще неэффективнее решать этот конфликт перехватами инициативы.

Я предлагаю описать в документе различные сценарии жизненных циклов временных групп. Пока дырок в описании многовато, и сходу неочевидно, какие конкретные технические проблемы покрываются придуманными сущностями.

2020-12-02 12:29 UTC, ahsima1 commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
В данном примере жилец может решать за электрика какого цвета будет кабель-канал, а как класть проводку жилец не может решать если сам не станет электриком. Может посоветовать, но конечное решение всё равно за электриком.

2020-12-02 12:35 UTC, adjofun requested changes
Общая проблема сформулирована.
Отсутствует модель проблемы, описывается конкретное решение. Причины принятий тех или иных решений в дизайне не описаны.

2020-12-02 13:15 UTC, sntxerror commented on content/wiki/working-groups.md
> +Если в рамках группы её участники не могут прийти к единому решению или решений несколько – группа предоставляет сравнение обсуждаемых решений для публичного голосования участникам, не входящим в гру
> Пока дырок в описании многовато

Ве дырки закрыть и не получится, будем улучшать по ходу дела. К тому же если кто-то захочет всех подвести  или навредить то можно это сделать и без создания рабочей группы. Нет цели защититься от всего плохого на свете и создать идеальный фреймворк.

Группа анализирует решения, если их больше чем одно – предлагает выбрать сообществу, предоставляя сравнение обоих опций. 

Не вижу проблемы и "виляния собакой" так как видишь ты. Опции предлагаются после экспертной оценки.

2020-12-02 13:17 UTC, sntxerror commented
> Общая проблема сформулирована.
> Отсутствует модель проблемы, описывается конкретное решение. Причины принятий тех или иных решений в дизайне не описаны.

Опиши пожалуйста свое предложение, я никогда не угадаю как ты это видишь и угодить тебе у меня цели нет. Помоги пожалуйста это улучшить если ты понимаешь как.

2020-12-02 13:25 UTC, sntxerror commented
> Общая проблема сформулирована.
> Отсутствует модель проблемы, описывается конкретное решение. Причины принятий тех или иных решений в дизайне не описаны.

Мне совсем не понятно при чем тут причины принятия тех или иных решений в дизайне.

2020-12-02 13:53 UTC, elsidoi commented on content/wiki/working-groups.md
> +Будучи участником группы, важно не только сохранять результат в рабочем состоянии, но и помогать участникам, не входящим в рабочу группу, в нем разбираться и пользоваться.
Третий раз об одном и том же. Может выше сделать ссылку в виде "См. Поддержка и Помощь"?

2020-12-02 14:20 UTC, elsidoi approved these changes
Погнали.

2020-12-03 07:51 UTC, imcatwhocode approved these changes
👍

2020-12-03 07:53 UTC, imcatwhocode commented
Текст сейчас кажется мне немного трудноватым для чтения, но с идеями я полностью согласен. После мерджа надо будет централизованно поработать над редактурой, как я понял, много у кого возникло желание этим заняться.

2020-12-07 21:00 UTC, frogsandsocks approved these changes

2020-12-27 19:43 UTC, z4fd commented
Мне откровенно неприятно, то что название этого пула не отражает его суть, я вижу в этом осознанную или нет манипуляцию и не уважение к сообществу

"Рабочие группы" и "Процесс принятия коллективных решений в бэкспейсе", чем по факту и является этот пулл, это не одно и то же. Пулл не добавляет страницу, а изменяет процесс 

Когда обсуждали Рабочие группы я каждый раз имел ввиду инструмент для упрощения участия в сообществе (https://www.noisebridge.net/wiki/FractalWorkingGroup). Сейчас значение вкладываемыe в "Рабочие группы", не хрена не очевидно. И поэтому до того как пулл не будет приведен к консистентности обсуждать содержание не буду

2021-01-12 16:09 UTC, van2048 reviewed
Я еще раз перечитал драфт и появился новый вопрос - по сути механика рабочих групп сильно меняют текущие правила игры. Если раньше для принятия решений было необходимо чтобы ни кто не был явно против (что делало невозможным принятие некоторых решений), то теперь не существует способа заблокировать решение рабочей группы.

На пример, я решил прорубить дверь из резидентской на улицу. Создал рабочую группу под эгидой пожарной безопасности. Нашел единомышленника, хотя драфт явно не запрещает РГ из 1 человека. Все кто против затеи не будут вступать в РГ и участвовать во всем этом мероприятии - их мнения начинают нести рекомендательных характер. Можно еще придумать пример про Сыча и генераторы.

Я не уверен плюс это или минус. Однако нужно иметь ввиду что результат злоупотребления старой концепций принятия решений была невозможность что-либо существенно изменить в спейсе, то теперь результат злоупотребления - невозможность что-либо блокировать в принципе.

2021-01-12 16:09 UTC, van2048 commented on content/wiki/working-groups.md
> +Перед выходом из группы важно обязательно сохранить и передать другим участникам все ресурсы для дальнейшей работы без вашего участия.
Что делать если я принес из дома свой инструмент, который мне понадобился дома?

2021-01-12 16:09 UTC, van2048 commented on content/wiki/working-groups.md
> +## Появление рабочей группы
В рабочих группах (РГ) в данный момент мне видится одна проблема. Когда человек теряет интерес к делам РГ, он скорее забьет на неё, чем объявит о своем выходе. Как минимум потому что ни когда не поздно выйти из РГ. Да и вообще выход видится больше как акт демонстративного протеста ( я - дартаньян а кругом пи*сы) ), других веских причин для выхода мне сложно представить. 

Это же относится и к закрытию рабочей группы. Закрыть ее ни когда не поздно, а веских причин закрывать РГ именно сейчас а не отложить на потом мне не видится. Опять же за исключением демонстрации протеста. Тем более многие long_term задачи можно завершить только волевым усилием ( аля невозможно завершить ремонт, можно его только остановить усилием воли ).

Я это все к тому, что с моей точки зрения РГ будут со временем только копиться и разрастаться новыми одноразовыми участниками. При этом уже через пару месяцев активность РГ спадет на нет группа не будет подавать признаков жизни, если конечно не найдется отдельно взятого энтузиаста.

SMART конечно здорово, но честно говоря я так и не смог приучить себя ни к одной методике личной эффективности, да и мне не известны такие люди. Все через это проходили). Конечно можно сказать что это про другое и вообще менеджмент и проектное управление, однако даже с этой же точки зрения можно привести аналогию с git flow, который в какой-то момент решили использовать. Мы используем git flow, скорее потому что каждому он знаком по работе, а не потому что он прям сильно подходит спейсу. У нас в репозиторий коммитят 1,5 человека раз в месяц, и ни кто не лезет в чужие ветки - с таким же успехом можно было ограничиться relese/develop ветками + рабочей веткой от develop с последующем PR. 


В качестве решения я предлагаю ввести life_time (месяц и 6 месяцев для разных Soldering Buddies, подразумевающих периодичность) для РГ, по истечении которого РГ будет автоматически закрываться и дальше, если интерес еще не угас, то активные участники создадут новую РГ.

2021-05-20 09:44 UTC, glitchcore commented
Предложение встретило возражения, за полгода не пришли к консенсусу, процессы изменились — закрываю PR.

2021-05-20 09:44 UTC, closed without merging