GH-345: Fix link to entrance photo on Contact page
b4ck5p4c3/0x08.in pull request #350
Opened 2021-02-05 11:40 UTC by imcatwhocode

Closes #345 

Добавляет картинку с картой и исправляет ссылку на неё на странице с контактами.

2021-02-05 12:55 UTC, sntxerror approved these changes

2021-02-05 13:23 UTC, sntxerror requested changes

2021-02-05 13:23 UTC, sntxerror commented on pages/contacts.mdx
> +<a href='/assets/map-entrance.jpg' alt='Ссылка на коллаж: фотография входа в хакспейс с выноской, показывающей точное расположение входа на карте' target='blank'>Так выглядит вход</a>
а почему `/static/assets/` вместо `/pages/assets/contacts/`?

2021-02-05 14:18 UTC, imcatwhocode commented on pages/contacts.mdx
> +<a href='/assets/map-entrance.jpg' alt='Ссылка на коллаж: фотография входа в хакспейс с выноской, показывающей точное расположение входа на карте' target='blank'>Так выглядит вход</a>
> а почему /static/assets/ вместо /pages/assets/contacts/?

Тогда не получится зашейрить простой линк вида https://0x08.in/assets/map-entrance.jpg, вместо этого получится дикая длиннющая ссылка на нужный чанк, которая ещё и не будет персистентной, например, если мы захотим положить по этому же урлу улучшенную картинку.

_В процесее, я ещё и не нашёл способа встроить в href ссылку на эту картинку в сбилженном виде, но это уже совсем другой разговор._

2021-02-05 14:28 UTC, elsidoi approved these changes
В примере вроде работает.
А со структурой папок можете и без меня разобраться.

2021-02-08 06:38 UTC, glitchcore approved these changes

2021-02-08 08:05 UTC, imcatwhocode commented on pages/contacts.mdx
> +<a href='/assets/map-entrance.jpg' alt='Ссылка на коллаж: фотография входа в хакспейс с выноской, показывающей точное расположение входа на карте' target='blank'>Так выглядит вход</a>
@sntxerror

2021-02-09 16:02 UTC, sntxerror approved these changes

2021-02-09 16:02 UTC, merged